# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 09:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apm', '0005_tenant_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('project_category', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_createdDate', models.DateField(auto_now_add=True)),
                ('project_startDate', models.DateField()),
                ('project_endDate', models.DateField()),
                ('project_assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_members', models.ManyToManyField(related_name='AllUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectEstimationGuidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_complexity', models.CharField(max_length=100)),
                ('task_complexity_point', models.IntegerField()),
                ('task_estimated_efforts', models.BigIntegerField()),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.Project')),
            ],
        ),
    ]
