# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apm', '0006_project_projectestimationguidelines'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_story_status', models.CharField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Done'), (4, 'ReOpen'), (5, 'Deferred'), (6, 'Close')], default=1, max_length=12)),
                ('storyDesc', models.CharField(max_length=1000)),
                ('startDate', models.DateField(auto_now_add=True)),
                ('roughEstimate', models.FloatField()),
                ('priority', models.IntegerField()),
                ('actual_effort', models.FloatField()),
                ('backlog_name', models.CharField(max_length=100)),
                ('assignee', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_requests_created', to=settings.AUTH_USER_MODEL)),
                ('fk_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('releaseName', models.CharField(max_length=100)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('releaseDate', models.DateField()),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('sprint_status', models.CharField(choices=[(1, 'Open'), (2, 'In Progress'), (3, 'Done'), (4, 'ReOpen'), (5, 'Deferred'), (6, 'Close')], default=1, max_length=12)),
                ('workinghours', models.CharField(max_length=100)),
                ('createdby', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apm.Project')),
                ('release_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.Release')),
            ],
        ),
        migrations.AddField(
            model_name='backlog',
            name='sprintId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apm.Sprint'),
        ),
    ]
