# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0007_auto_20161213_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='release',
            old_name='projectid',
            new_name='fk_project',
        ),
        migrations.RenameField(
            model_name='sprint',
            old_name='project',
            new_name='fk_project',
        ),
        migrations.AlterField(
            model_name='backlog',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backlog_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
