# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apm', '0008_auto_20161214_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='created_by',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
